# -*- coding: utf-8 -*-
"""programing Practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uzXM6_O09joDV9Vdwj7REECEzzFl2uGg

# **First index of a number in a list**

**Method 1**
"""

def firstIndex(l,x):
  length = len(l)
  if length == 0:
    return -1
  elif l[0] == x:
    return 1
  else:
    smallerOutput = firstIndex(l[1:],x)
  if smallerOutput == -1:
    return -1
  else:
    return smallerOutput + 1
 # return smallerOutput
  
  


l = list(map(int,input().split()))
x = int(input())
print(firstIndex(l,x))

"""**Method 2**"""

def firstIndex_s(l,x,start):
  length = len(l)
  if start > length:
    return -1
  elif l[start] == x:
    return 1
  else:
    smallerOutput = firstIndex(l,x,start + 1)
  if smallerOutput == -1:
    return -1
  else:
    return smallerOutput + 1
 # return smallerOutput
  
  


l = list(map(int,input().split()))
x = int(input())
print(firstIndex(l,x))

"""# **Last index of a number in a list**"""

def lastIndex (l,x ):
  length = len(l)
  if length == 0:
    return -1
  smallerOutput = lastIndex(l[1:],x)
  if smallerOutput !=-1:
    return smallerOutput + 1
  else:
    if l[0] == x:
      return 1
    else:
      return -1


l = list(map(int, input().split()))
n = int(input())
print(lastIndex(l,n))

"""# **Check if the list is sorted or not**"""

def SortOrNot(l):
  length = len(l)
  if length == 0 or length == 1:
    return True

  if l[0] > l[1]:
    return False
    
  smallerOutput = SortOrNot(l[1:])
  if smallerOutput:
    return True
  else:
    return False

  

#start = 1
l = list(map(int,input().split()))
print(SortOrNot(l))

"""# **Substring**"""

def substring(s):
  l = []
  length = len(s)
  if length == 0:
    return
  else:
    


l = []
str = input()
l = substring(str)
print(l)

